### ISSUE TITLE
Fix this problem it's not working ...

### ISSUE THREAD

**Issue by hxlxmj** [T-Dynamos/Infector#3]
Do you want to change App Name [y/n] = n                               
                                                                       
[>] Finding smali launcher : MainActivity.smali                        
rm: cannot remove 'out': No such file or directory                     
rm: cannot remove 'ramp': No such file or directory                    
rm: cannot remove 'result': No such file or directory                  
rm: cannot remove 'twelv.txt': No such file or directory               
rm: cannot remove '2': No such file or directory                       
grep: Invalid range end                                                
cat: result: No such file or directory                                 
Traceback (most recent call last):                                     
  File "/home/kali/Desktop/tools/Infector/binder.py", line 539, in <module>                                                                   
    main()                                                             
  File "/home/kali/Desktop/tools/Infector/binder.py", line 538, in main
    pay_type()                                                         
  File "/home/kali/Desktop/tools/Infector/binder.py", line 414, in pay_type                                                                   
    line = subprocess.check_output("cat result",shell=True)            
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output   
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,   
  File "/usr/lib/python3.9/subprocess.py", line 528, in run            
    raise CalledProcessError(retcode, process.args,                    
subprocess.CalledProcessError: Command 'cat result' returned non-zero exit status 1.

**Comment by T-Dynamos** [comment]
Just try reinstall tool
